<a href="https://colab.research.google.com/github/anandababugudipudi/Breast-Cancer-Prediction-using-DecisionTreeClassifier/blob/main/Breast_Cancer_Prediction_using_DecisionTreeClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
cancer_data = load_breast_cancer()

In [ ]:
X = cancer_data.data
y = cancer_data.target
print(X.shape)
print(y.shape)

(569, 30)
(569,)


In [ ]:
#param_grid = {'max_depth': np.arange(1, 10)}

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 122)

In [ ]:
model = DecisionTreeClassifier(criterion = 'gini', max_depth = 5)

In [ ]:
'''
tree = GridSearchCV(model, param_grid)
tree.fit(X_train, y_train)
print("Best parameter with Grid Search: ", tree.best_params_)
grid_predictions = tree.predict(X_test)
print(confusion_matrix(y_test, grid_predictions))
print(accuracy_score(y_test, grid_predictions))
'''

In [ ]:
predicted = cross_validate(model, X, y, cv = 10)
print(np.mean(predicted['test_score']))

0.9262218045112782


[[ 8  0  0]
 [ 0 10  1]
 [ 0  2  9]]
0.9
